service: dappyer-backend-api

useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.gendername.com
    basePath: ''
    stage: ${opt:stage, self:provider.stage, "dev"}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs18.x


functions:
  main:
    handler: dist/main.handler
    timeout: 200
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'