name: deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: build image
        run: docker build -t gendername .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: delete container if exists
        run: docker rm -f gendername || true
      - name: run container
        run: docker run -d --name gendername -p 5481:5481 gendername
